// list of media files

var mediaFiles = [
    // videos
    "media/big_buck_bunny.mov",
    "media/Blobs.mov",
    "media/Carnival.mov",
    "media/Golden Gate Bridge.mov",
    "media/Jellyfish.mov",
    "media/Sintel 1024.mp4",
    "media/Train.mov",
    "media/Water & Wind.mov",

    // images
    "media/Ageeba.jpg",
    "media/Aurora Borealis.jpg",
    "media/Bakony Falls.jpg",
    "media/Blue Moment.jpg",
    "media/Canyon Sunset.jpg",
    "media/Eenlightenment.jpg",
    "media/Endeavours Launch.jpg",
    "media/Herbert Lake.jpg",
    "media/Horsehead Nebula.jpg",
    "media/In Saturns Shadow by Cassini.jpg",
    "media/La Tour Eiffel.jpg",
    "media/Milford Sound Sunrise.jpg",
    "media/New York Sky.jpg",
    "media/Orange Days.jpg",
    "media/Pocaterra Cirque.jpg",
    "media/Resistance.jpg",
    "media/Salish Sea.jpg",
    "media/The Birth of Europa.jpg",
    "media/The Earth.jpg",
    "media/The Opal Lake.jpg",
    "media/Tree in The Mist.jpg"
];

var transitionTypes = [
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BAR_WIPE_LR,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BAR_WIPE_TB,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BOX_WIPE_TL,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BOX_WIPE_TR,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BOX_WIPE_BR,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BOX_WIPE_BL,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_FOUR_BOX_WIPE_CI,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_FOUR_BOX_WIPE_CO,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BARNDOOR_V,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BARNDOOR_H,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BOX_WIPE_TC,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BOX_WIPE_RC,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BOX_WIPE_BC,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BOX_WIPE_LC,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DIAGONAL_TL,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DIAGONAL_TR,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BOWTIE_V,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BOWTIE_H,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BARNDOOR_DBL,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BARNDOOR_DTL,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_MISC_DIAGONAL_DBD,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_MISC_DIAGONAL_DD,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_VEE_D,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_VEE_L,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_VEE_U,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_VEE_R,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BARNVEE_D,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BARNVEE_L,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BARNVEE_U,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_BARNVEE_R,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_IRIS_RECT,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_CLOCK_CW12,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_CLOCK_CW3,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_CLOCK_CW6,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_CLOCK_CW9,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_PINWHEEL_TBV,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_PINWHEEL_TBH,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_PINWHEEL_FB,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_FAN_CT,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_FAN_CR,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DOUBLEFAN_FOV,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DOUBLEFAN_FOH,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SINGLESWEEP_CWT,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SINGLESWEEP_CWR,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SINGLESWEEP_CWB,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SINGLESWEEP_CWL,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DOUBLESWEEP_PV,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DOUBLESWEEP_PD,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DOUBLESWEEP_OV,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DOUBLESWEEP_OH,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_FAN_T,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_FAN_R,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_FAN_B,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_FAN_L,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DOUBLEFAN_FIV,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DOUBLEFAN_FIH,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SINGLESWEEP_CWTL,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SINGLESWEEP_CWBL,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SINGLESWEEP_CWBR,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SINGLESWEEP_CWTR,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DOUBLESWEEP_PDTL,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_DOUBLESWEEP_PDBL,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SALOONDOOR_T,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SALOONDOOR_L,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SALOONDOOR_B,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_SALOONDOOR_R,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_WINDSHIELD_R,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_WINDSHIELD_U,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_WINDSHIELD_V,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_WINDSHIELD_H,
    MediaTimelineTransitionOperation.TRANSITION_TYPE_CROSSFADE
];
